title: OpenSource-Practise
author: McCrudd3n
#email: <Private>@<domain>.com
description: > # this means to ignore newlines until "baseurl:"
  Knowledge has a beginning but no end. 

# social links
twitter_username: your-twitter-handle
#github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
