##This is a simple start up script with Ansible, I connect via Vagrant
## Creating a virtual test bed
---
- hosts: all
  become: true
  tasks:
    - name: Connection Test
      ping: 
    - name: Install PHP
      apt: name=php5-cli state=present update_cache=yes
    - name: Install mySQL
      apt: name=mysql-server-5.6 state=present
